package com.buddies.services.userprofile.types;

import java.util.List;

public interface Language {
	public static List<String> all() {
		return List.of(
			"CHINESE", "SPANISH", "ENGLISH", "BENGALI", "HINDI", "PERSIAN", "PORTUGUESE", "RUSSIAN", "JAPANESE", "GERMAN", "JAVANESE", "KOREAN", "FRENCH",
			"VIETNAMESE", "TELUGU", "MARATHI", "TAMIL", "TURKISH", "URDU", "GUJARATI", "POLISH", "ARABIC", "UKRAINIAN", "ITALIAN", "MALAYALAM", "KANNADA",
			"ORIYA", "PANJABI", "SUNDA", "ROMANIAN", "BHOJPURI", "AZERBAIJANI", "FARSI", "MAITHILI", "HAUSA", "BURMESE", "SERBO", "AWADHI", "THAI", "DUTCH",
			"YORUBA", "SINDHI", "UZBEK", "MALAY", "AMHARIC", "INDONESIAN", "IGBO", "TAGALOG", "NEPALI", "SARAIKI", "CEBUANO", "ASSAMESE", "HUNGARIAN",
			"CHITTAGONIAN", "MADURA", "SINHALA", "HARYANVI", "MARWARI", "CZECH", "GREEK", "MAGAHI", "CHHATTISGARHI", "DECCAN", "BELARUSAN", "ZHUANG",
			"SOMALI", "MALAGASY", "RWANDA", "ZULU", "BULGARIAN", "SWEDISH", "LOMBARD", "OROMO", "KAZAKH", "ILOCANO", "TATAR", "FULFULDE", "UYGHUR",
			"HAITIAN", "NAPOLETANO", "KHMER", "AKAN", "HILIGAYNON", "KURMANJI", "SHONA"
		);
	}
}
